---
- name: "vCenter Connectivity Test"
  hosts: "{{ ansible_host | default('all') }}"
  any_errors_fatal: true
  gather_facts: true
  connection: local

  module_defaults:
    group/vmware:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_user_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"

  roles:
    - role: provisioning/vcenter_connection
      tags:
        - connectivity
        - always