---
# ===================================================================================
# Zone: XXXXXX-VA — vCenter and environment configuration
# vCenter connection defaults for XXXXXX-VA
# ===================================================================================

config_vcenter_datacenter: "xxxxxxxxxxxxxx"
config_vcenter_cluster: "xxxxxxxxxxxxx"
config_vcenter_datastore: "xxxxxxxxxxxxxxx"
config_vm_folder: "xxxxxxxxxxxxxxxxxxxx"

config_vcenter_resource_pool: ""

# Zone-wide template and environment
config_vm_template: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
config_vm_environment: "xxxxxxxxxxxxxxxxxx"